---
title: "EGIS Service Information, Tools, and Resources"
subtitle: "This document summarizes specific use cases and procedures for using data and service endpoints. "
format: html
---

## Welcome {#welcome}

These docs help you use the services provided by the Earthdata Search Platform and NASA's CMR STAC. Its purpose is to be a resource for interacting with NASA data and provide use cases as well as behaviors in ArcGIS Pro and open-source software. 

## Known Limitations and Expected Behaviors {#kleb}
:::: {layout="[0.25, 0.25, 0.25, 0.25]"}

:::{#firstcol}
### Overview and Guidance

* [Purpose of the Documentation Hub](/kleb-project/index.html)
:::

:::{#secondcol}
### EGIS Limitations

* [No Download](/kleb-project/egis-limitations/no_download.qmd)
* [Active Development](/kleb-project/egis-limitations/active_dev.qmd)
* [Authentication](/kleb-project/egis-limitations/authentication.qmd)
* [Image Service Capability Index](/kleb-project/egis-limitations/service_capability.qmd)
:::

:::{#thirdcol}
### Services

* [Map Services](/kleb-project/services/map_services.qmd)
* [Feature Services](/kleb-project/services/feature_services.qmd)
* [Image Services](/kleb-project/services/image_services.qmd)
* [OGC Services](/kleb-project/services/ogc_services.qmd)
* [Service Announcements](/kleb-project/services/announcements.qmd)
:::

:::{#fourthcol}
### Product and Platform Behavior

* [Web vs Desktop](/kleb-project/behaviors/web_vs_desktop.qmd)
* [Pop-Ups](/kleb-project/behaviors/pop_up.qmd)
* [Version-Specific Behavior](/kleb-project/behaviors/versioning.qmd)
* [OGC vs COTS Endpoints](/kleb-project/behaviors/endpoints.qmd)
:::

::::

:::: {layout="[0.33, 0.33, 0.33]"}

:::{#firstcol}
### Application Integrations & Tools

* [Dashboards](/kleb-project/tools/dashboards.qmd)
* [Experience Builder](/kleb-project/tools/experience_builder.qmd)
* [Web AppBuilder](/kleb-project/tools/appbuilder.qmd)
* [Third Party Tools](/kleb-project/tools/third_party.qmd)
:::

:::{#secondcol}
### Data Standards & Managements

* [Data Standards & Managements](/kleb-project/standards/index.qmd)
:::

:::{#thirdcol}
### Resources

* [General Documentation Links](/kleb-project/resources/index.html)
* [How-To](/kleb-project/resources/how_to.qmd)
* [External Resources](/kleb-project/resources/external_resources.qmd)

:::

::::
## Tutorials

To learn from examples, see the [Tutorial Page](/tutorials/index.qmd) for Jupyter Notebooks on how to use EGIS specific data services and images. 

## EGIS Content Release Tracker

| Release | Summary | Date | Owner |
|---------|---------|------|-------|
| 1.0 | Initial webpage build and population of existing content | 12/12/2025 | ryan-barnhart | 

</div> <!-- /.main-content -->
</div> <!-- /.page-with-left-sidebar -->

